###!/bin/bash -e
#
# Much of this camre frome here:
# https://github.com/wpilibsuite/FRCVision-pi-gen/
#

		
# Network Tables
# Install pynetworktables
# This is preferred communication with between robot, controllstation and vision processor.
# ZMQ latency would be 200microseconds to 1.5ms
# Little Data available for NetworkTables
#########################
cd ~
wget -nc -nv -O pynetworktables.tar.gz https://github.com/robotpy/pynetworktables/archive/2019.0.2.tar.gz
tar xzf pynetworktables.tar.gz
rm pynetworktables.tar.gz
mv pynetworktables-* pynetworktables
echo "__version__ = '2019.0.2'" > pynetworktables/ntcore/version.py
cd pynetworktables
python3 setup.py build
sudo python3 setup.py install
python3 setup.py clean

# Raspbian toolchain
####################
# this is likely not needed on fresh system
#cd ~
#wget -nc -nv https://github.com/wpilibsuite/raspbian-toolchain/releases/download/v2.1.0/Raspbian10-Linux-Toolchain-8.3.0.tar.gz
#tar xzf Raspbian10-Linux-Toolchain-*.tar.gz
#rm Raspbian10-Linux-Toolchain-*.tar.gz
## add to .bashrc
#export PATH=/home/pi/raspbian10/bin:${PATH}
#export PKG_CONFIG_DIR=
#export PKG_CONFIG_LIBDIR=/usr/lib/arm-linux-gnueabihf/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:/home/pi/pkconfig
#export PKG_CONFIG_SYSROOT_DIR=/
#mkdir ~/pkgconfig
#cd ~/pkgconfig
#wget https://raw.githubusercontent.com/wpilibsuite/FRCVision-pi-gen/frcvision/stage3/01-sys-tweaks/files/pkgconfig/cameraserver.pc
#wget https://raw.githubusercontent.com/wpilibsuite/FRCVision-pi-gen/frcvision/stage3/01-sys-tweaks/files/pkgconfig/cscore.pc
#wget https://raw.githubusercontent.com/wpilibsuite/FRCVision-pi-gen/frcvision/stage3/01-sys-tweaks/files/pkgconfig/ntcore.pc
#wget https://raw.githubusercontent.com/wpilibsuite/FRCVision-pi-gen/frcvision/stage3/01-sys-tweaks/files/pkgconfig/wpilibc.pc
#wget https://raw.githubusercontent.com/wpilibsuite/FRCVision-pi-gen/frcvision/stage3/01-sys-tweaks/files/pkgconfig/wpiutil.pc
#cp ~/opencv/build/unix-install/opencv.pc ~/pkgconfig/
## OpenCV 4
##cp ~/opencv/build/unix-install/opencv4.pc ~/pkgconfig/
##ln -sf ~/pkgconfig/opencv4.pc ~/pkconfig/opencv.pc 

# wpilib
#########################
cd ~
# git clone https://github.com/wpilibsuite/allwpilib.git
wget https://github.com/wpilibsuite/allwpilib/archive/v2019.4.1.tar.gz
tar xzf v2019.4.1.tar.gz
rm v2019.4.1.tar.gz
mv allwpilib-2019.4.1 allwpilib
# Patch Code for OpenCV2 Version 4
# This is not yet completed and would need some more work.
# You would need to google to find solutions for include files and JPEG quality issue
#allwpilib/cscore/src/main/native/cpp/CvSinkImpl.cpp
#allwpilib/cscore/src/main/native/cpp/CvSourceImpl.cpp
#allwpilib/cscore/src/main/native/cpp/Frame.cpp
#CV_IMWRITE_JPEG_QUALITY

# Build wpiutil (gradel seems to focus on Windows Platform)
rm -rf build
mkdir -p build
cd build
cmake -D WITHOUT_ALLWPILIB=OFF \
    -D CMAKE_BUILD_TYPE=Release \
    -D OPENCV_JAR_FILE=`ls /usr/local/java/opencv-348.jar` \
    -D OPENCV_JNI_FILE=`ls /usr/local/lib/libopencv_java348.so` \
    -D OpenCV_DIR=/usr/local/share/opencv4 \
    -D THREADS_PTHREAD_ARG=-pthread \
    -D BUILD_SHARED_LIBS=ON \
    -D CMAKE_INSTALL_PREFIX=/usr/local ..
# cmake-gui ../
# check all options, cofigure, generate
make -j3 
sudo make install
# don't make clean, some autogenerated files are needed for the robotpy install

# Install robotpy-cscore (pythong binding to cscore)
###########################
# add to .bashrc
# :~/pkgconfig
# to line with export PKG_CONFIG_LIBDIR:~/pkgconfig
#
# Get the robotpy score, binds cscore with pythong
cd ~
git clone https://github.com/robotpy/robotpy-cscore.git
# echo "__version__ = '2019.1.1.custom'" > robotpy-cscore/cscore/version.py
# setup.py creates the verfsion above
cd robotpy-cscore
#wget https://raw.githubusercontent.com/wpilibsuite/FRCVision-pi-gen/frcvision/stage3/01-sys-tweaks/files/robotpy-cscore.patch
#patch -p0 < "robotpy-cscore.patch"
# needs pybind11
wget -nc -nv -O pybind11.tar.gz https://github.com/pybind/pybind11/archive/v2.4.3.tar.gz
rm -rf pybind11
tar xzf pybind11.tar.gz
rm pybind11.tar.gz
mv pybind11-* pybind11
cd pybind11
python3 setup.py build
sudo python3 setup.py install
cd ..
# install Python sources (cameraserver etc)
sh -c 'tar cf - cscore' |  sh -c "cd /usr/local/lib/python3.7/dist-packages && sudo tar xf -"
#
# Build robotpy-cscore
#
# Making sure of pre-requs
sudo pip3 install --upgrade pip
sudo pip3 install --upgrade setuptools
sudo pip3 install --upgrade numpy
# provide link to source 
ln -fs ~/allwpilib/cscore/ ~/robotpy-cscore/cscore_src/cscore
ln -fs ~/allwpilib/wpiutil/ ~/robotpy-cscore/cscore_src/wpiutil
#edit setup.py and change the following section
#include_dirs=[
#	"pybind11/include",
#	"cscore_src/cscore/src/main/native/include",
#	"cscore_src/cscore/src/main/native/cpp",
#	"cscore_src/wpiutil/src/main/native/include",
#	"cscore_src/wpiutil/src/main/native/libuv",
#	get_numpy_include(),
#],
python3 setup.py build
sudo python3 setup.py install

# Other Option that might work
# sudo pip3 install --no-build-isolation robotpy-cscore
